### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by Prajwal-Koirala** [bonedaddy/vcaptcha#1]
You know what they say;
A single picture is worth 1000 words.

**Comment by bonedaddy** [comment]
there should be an example of implementing a HTTP server that shows how you can retrieve a ticket to solve, and how you can submit a ticket to verify that you did compute the VDF correctly, and that it hasn't already been verified. While writing this I realized that I forgot to include an example of how you would use the JWT to prevent access to certain routes by those who havent submitted a valid ticket so I just pushed a new commit that should show that.

I'm currently extracting this from a different project I have on a local gitea server, so its missing an example of how a client would make a request for a new ticket, submit a valid ticket, etc... I'll have that done within the next few hours. however if you're familiar with HTTP requests in golang it should be fairly simple:

* send http request to /captcha_request
* take received body and unmarshal it into a `ticket.Ticket` struct
* Run `ticket.Solve()`
* Marshal the struct
* send http request to /captcha_solve with the marshaled struct bytes
* take returned JWT insert into a header named `Authorization` with the value `BEARER <insert-jwt-here>`

**Comment by bonedaddy** [comment]
I've updated the example to showcase how you would retrieve a ticket, solve the ticket, and use the solved ticket to access protected routes. If you're interested in taking a look the client code starts here https://github.com/bonedaddy/vcaptcha/blob/bddba8bb5e98c9e5298330a4d47d98bc760b1b0f/examples/main.go#L71

Im going to  close this issue as this should now suffice for a demo if you disagree please re-open the issue, thanks.
